/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VtnPrincipal.java
 *
 * Created on 15/12/2010, 06:11:08 PM
 */

package logictable.vista;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JTabbedPane;
import javax.swing.plaf.basic.BasicComboPopup;
import javax.swing.text.BadLocationException;
import logictable.ayuda.Ayuda;
import logictable.modelo.ArchivosLtt;

/**
 *
 * @author EDÚ
 */
public class VtnPrincipal extends javax.swing.JFrame {

    /** Creates new form VtnPrincipal */
    public VtnPrincipal() {
        initComponents();
        ImageIcon im=new ImageIcon(getClass().getResource("/logictable/logos/Captura.png"));
        Image imag=im.getImage();
        this.setIconImage(imag);

        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabla = new javax.swing.JTabbedPane();
        pnlImagen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlBarraHerram = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miNuevo = new javax.swing.JMenuItem();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        miGuardarcomo = new javax.swing.JMenuItem();
        miImprimir = new javax.swing.JMenuItem();
        miCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        pnlTabla.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                pnlTablaComponentRemoved(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIC TABLE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlImagen.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/logos/Captura.PNG"))); // NOI18N
        pnlImagen.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlImagen, java.awt.BorderLayout.CENTER);

        pnlBarraHerram.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/document_32.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo ");
        btnNuevo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNuevo.setMaximumSize(new java.awt.Dimension(35, 37));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/save_32.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnGuardar.setMaximumSize(new java.awt.Dimension(35, 37));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/folder_32.png"))); // NOI18N
        btnAbrir.setToolTipText("Abrir");
        btnAbrir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAbrir.setMaximumSize(new java.awt.Dimension(35, 37));
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/print_32.png"))); // NOI18N
        jButton5.setToolTipText("Imprimir");
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.setMaximumSize(new java.awt.Dimension(35, 37));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/search_32.png"))); // NOI18N
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.setMaximumSize(new java.awt.Dimension(35, 37));

        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.setMaximumSize(new java.awt.Dimension(35, 37));

        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton8.setMaximumSize(new java.awt.Dimension(35, 37));

        javax.swing.GroupLayout pnlBarraHerramLayout = new javax.swing.GroupLayout(pnlBarraHerram);
        pnlBarraHerram.setLayout(pnlBarraHerramLayout);
        pnlBarraHerramLayout.setHorizontalGroup(
            pnlBarraHerramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraHerramLayout.createSequentialGroup()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        pnlBarraHerramLayout.setVerticalGroup(
            pnlBarraHerramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraHerramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAbrir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBarraHerram, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Archivo");

        miNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/document_16.png"))); // NOI18N
        miNuevo.setText("Nuevo");
        miNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(miNuevo);

        miAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/folder_16.png"))); // NOI18N
        miAbrir.setText("Abrir");
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(miAbrir);

        miGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/save_16.png"))); // NOI18N
        miGuardar.setText("Guardar");
        miGuardar.setEnabled(false);
        miGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(miGuardar);

        miGuardarcomo.setText("Guardar Como");
        miGuardarcomo.setEnabled(false);
        miGuardarcomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGuardarcomoActionPerformed(evt);
            }
        });
        jMenu1.add(miGuardarcomo);

        miImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/print_16.png"))); // NOI18N
        miImprimir.setText("Imprimir");
        miImprimir.setEnabled(false);
        miImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImprimirActionPerformed(evt);
            }
        });
        jMenu1.add(miImprimir);

        miCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/delete_16.png"))); // NOI18N
        miCerrar.setText("Cerrar");
        miCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(miCerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/cut.png"))); // NOI18N
        jMenuItem7.setText("Cortar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/copy.png"))); // NOI18N
        jMenuItem8.setText("Copiar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logictable/vista/Iconos/paste.png"))); // NOI18N
        jMenuItem9.setText("Pegar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-830)/2, (screenSize.height-659)/2, 830, 659);
    }// </editor-fold>//GEN-END:initComponents

    private void miNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoActionPerformed
            nuevo("","Nuevo");
    }//GEN-LAST:event_miNuevoActionPerformed

    private void nuevo(String texto, String Nombre){
            PnlPrincipal pn=new PnlPrincipal(pnlTabla,texto, Nombre);
            pnlTabla.add(pn);
            pnlTabla.setSelectedIndex(pnlTabla.getComponentCount()-1);
            JPanel aux=new JPanel(new BorderLayout());
            aux.add(pnlTabla,"Center");
            aux.add(pnlBarraHerram,"North");
          //  paneles.add(pn);
            this.setContentPane(aux);
            this.setVisible(true);
            miGuardar.setEnabled(true);
            miGuardarcomo.setEnabled(true);
            miImprimir.setEnabled(true);
            JPanel p=new JPanel();

    }

    private void miAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirActionPerformed
        try {
            String str=ArchivosLtt.abrir(this);
            String nomb=ArchivosLtt.getNombreArchivo(this);
            nuevo(str, nomb);
        } catch (BadLocationException ex) {
            Logger.getLogger(VtnPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_miAbrirActionPerformed

    private void miGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardarActionPerformed
        String str=((PnlPrincipal)pnlTabla.getSelectedComponent()).getTexto();
        try {
            ArchivosLtt.guardar(str);
        } catch (IOException ex) {
            Logger.getLogger(VtnPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miGuardarActionPerformed

    private void miGuardarcomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardarcomoActionPerformed
        fc =new JFileChooser();
        fc.setVisible(true);
        fc.showDialog(this, "Guardar Como");
    }//GEN-LAST:event_miGuardarcomoActionPerformed

    public JTabbedPane obtenerTabbedPane(){
        return pnlTabla;
    }

    private void miImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImprimirActionPerformed
            new Ayuda(this);
    }//GEN-LAST:event_miImprimirActionPerformed

    private void pnlTablaComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlTablaComponentRemoved
            if(pnlTabla.getComponents().length==0){
                    JPanel aux=new JPanel(new BorderLayout());
                    aux.add(pnlImagen,"Center");
                    aux.add(pnlBarraHerram,"North");
                    this.setContentPane(aux);
                    miGuardar.setEnabled(false);
                    miGuardarcomo.setEnabled(false);
                    miImprimir.setEnabled(false);
            }
    }//GEN-LAST:event_pnlTablaComponentRemoved

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
         
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void miCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCerrarActionPerformed
            ((PnlPrincipal)pnlTabla.getSelectedComponent()).cerrar();
    }//GEN-LAST:event_miCerrarActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
            new Ayuda();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
            miNuevoActionPerformed(evt);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            miGuardarActionPerformed(evt);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        miAbrirActionPerformed(evt);
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ((PnlPrincipal)pnlTabla.getSelectedComponent()).getTextPane().cut();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
            ((PnlPrincipal)pnlTabla.getSelectedComponent()).getTextPane().copy();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
            ((PnlPrincipal)pnlTabla.getSelectedComponent()).getTextPane().paste();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem miAbrir;
    private javax.swing.JMenuItem miCerrar;
    private javax.swing.JMenuItem miGuardar;
    private javax.swing.JMenuItem miGuardarcomo;
    private javax.swing.JMenuItem miImprimir;
    private javax.swing.JMenuItem miNuevo;
    private javax.swing.JPanel pnlBarraHerram;
    private javax.swing.JPanel pnlImagen;
    private javax.swing.JTabbedPane pnlTabla;
    // End of variables declaration//GEN-END:variables
//    private List<PnlPrincipal> paneles=new ArrayList<PnlPrincipal>();
    private JFileChooser fc=new JFileChooser();
}
